# Generated by Django 5.1.7 on 2025-03-22 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='about_me',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='picture_profile',
            field=models.ImageField(blank=True, upload_to='profile_pictures/'),
        ),
    ]
