# Generated by Django 5.1.7 on 2025-03-21 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Preparat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=200)),
                ('descriere', models.TextField()),
                ('data_adaugare', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
